export const TOOL_VERSION = "0.1.0";

export const EXIT_CODES = {
  INVALID_ARGS: 2,
  RESOLUTION_FAILED: 3,
  INDEX_UNREADABLE: 4,
  REF_NOT_FOUND: 5,
  SCHEMA_MISMATCH: 6,
  INTERNAL_ERROR: 7
};

export const DEFAULTS = {
  maxResults: 5,
  maxChars: 2000
};

export const ERROR_CODE_NAMES = {
  [EXIT_CODES.INVALID_ARGS]: "INVALID_ARGS",
  [EXIT_CODES.RESOLUTION_FAILED]: "RESOLUTION_FAILED",
  [EXIT_CODES.INDEX_UNREADABLE]: "INDEX_UNREADABLE",
  [EXIT_CODES.REF_NOT_FOUND]: "REF_NOT_FOUND",
  [EXIT_CODES.SCHEMA_MISMATCH]: "SCHEMA_MISMATCH",
  [EXIT_CODES.INTERNAL_ERROR]: "INTERNAL_ERROR"
};
