export const TOOL_VERSION = "1.0.0";

export const EXIT_CODES = {
  INVALID_ARGS: 2,
  RESOLUTION_FAILED: 3,
  INDEX_UNREADABLE: 4,
  REF_NOT_FOUND: 5,
  SCHEMA_MISMATCH: 6,
  INTERNAL_ERROR: 7,
  DISCOVERY_FAILED: 8,
  AMBIGUOUS_MATCH: 9,
  FETCH_BLOCKED: 10,
  FETCH_RATE_LIMITED: 11,
  POLICY_VIOLATION: 12
};

export const DEFAULTS = {
  maxResults: 5,
  maxChars: 2000,
  fetchMaxFiles: 2000,
  fetchMaxTotalBytes: 20 * 1024 * 1024,
  surfaceMaxSymbols: 200,
  surfaceMaxExamples: 3,
  surfaceMaxFiles: 2000,
  surfaceMaxBytes: 20 * 1024 * 1024
};

export const ERROR_CODE_NAMES = {
  [EXIT_CODES.INVALID_ARGS]: "INVALID_ARGS",
  [EXIT_CODES.RESOLUTION_FAILED]: "RESOLUTION_FAILED",
  [EXIT_CODES.INDEX_UNREADABLE]: "INDEX_UNREADABLE",
  [EXIT_CODES.REF_NOT_FOUND]: "REF_NOT_FOUND",
  [EXIT_CODES.SCHEMA_MISMATCH]: "SCHEMA_MISMATCH",
  [EXIT_CODES.INTERNAL_ERROR]: "INTERNAL_ERROR",
  [EXIT_CODES.DISCOVERY_FAILED]: "DISCOVERY_FAILED",
  [EXIT_CODES.AMBIGUOUS_MATCH]: "AMBIGUOUS_MATCH",
  [EXIT_CODES.FETCH_BLOCKED]: "FETCH_BLOCKED",
  [EXIT_CODES.FETCH_RATE_LIMITED]: "FETCH_RATE_LIMITED",
  [EXIT_CODES.POLICY_VIOLATION]: "POLICY_VIOLATION"
};
